import campeonatos from "../asserts/campeonatos.jpg";
import seminario from "../asserts/seminario.jpg";

export const infosEvents = [
  {
    name: "Campeonato",
    img: campeonatos,
    description: "Campeonato nacional",
    date: "04/04/2021",
    regiao: "Norte, Nordeste",
    pais: "Brasil",
    id: 1,
  },
  {
    name: "seminario",
    img: seminario,
    description: "Seminário nacional",
    date: "04/04/2021",
    regiao: "Norte, Nordeste",
    pais: "Brasil",
    id: 2,
  },
  {
    name: "seminario",
    img: seminario,
    description: "Seminário nacional",
    date: "04/04/2021",
    regiao: "Norte, Nordeste",
    pais: "Brasil",
    id: 2,
  },
  {
    name: "seminario",
    img: seminario,
    description: "Seminário nacional",
    date: "04/04/2021",
    regiao: "Norte, Nordeste",
    pais: "Brasil",
    id: 2,
  },
  {
    name: "seminario",
    img: seminario,
    description: "Seminário nacional",
    date: "04/04/2021",
    regiao: "Norte, Nordeste",
    pais: "Brasil",
    id: 2,
  },
  {
    name: "seminario",
    img: seminario,
    description: "Seminário nacional",
    date: "04/04/2021",
    regiao: "Norte, Nordeste",
    pais: "Brasil",
    id: 2,
  },
  {
    name: "seminario",
    img: seminario,
    description: "Seminário nacional",
    date: "04/04/2021",
    regiao: "Norte, Nordeste",
    pais: "Brasil",
    id: 2,
  },
];
